### ISSUE TITLE
不能正常使用

### ISSUE THREAD

**Issue by yao206cc** [Dali-Team/vscode-ts-in-markdown#2]
我遇到了问题,vs code 扩展商店下载后不能正常使用.
报错信息如下:
![image](https://user-images.githubusercontent.com/29507751/133365523-aa9d88c2-5515-478c-9428-a257f0d7746e.png)
![image](https://user-images.githubusercontent.com/29507751/133365561-6495820f-c48f-4f53-be70-65ad0fb4fbe4.png)
期待答复

**Comment by Amour1688** [comment]
发了个新版本
